---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: telegraf-agent
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-agent
  namespace: monitoring
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: telegraf-agent
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf-agent
subjects:
- kind: ServiceAccount
  name: telegraf-agent
  namespace: monitoring
