global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: server-1

remote_write:
  - url: http://127.0.0.1:8428/api/v1/write

scrape_configs:
  - job_name: "prom-server"
    static_configs:
      - targets:
          - 127.0.0.1:9090
  - job_name: "node"
    static_configs:
      - targets:
          - 127.0.0.1:9100
  - job_name: "grafana"
    static_configs:
      - targets:
          - 127.0.0.1:3000
  - job_name: "vm"
    static_configs:
      - targets:
          - 127.0.0.1:8428            
