version: "3.9"
services:
  vm:
    image: "victoriametrics/victoria-metrics"
    ports:
      - "8428:8428"
    volumes:
      - ./victoria-metrics-data :/victoria-metrics-data       
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"  
    volumes: 
      - ./grafana/config/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/config/dashboards/:/etc/grafana/provisioning/dashboards/ 
      - ./grafana/dashboards/:/var/grafana/dashboards/
  prometheus:
    image: "prom/prometheus"
    volumes:
        - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"        
networks: 
  default: 
    external: 
      name: dc-simulator 
