global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: edge-1

remote_write:
  - url: http://10.164.246.145:8428/api/v1/write
    queue_config:
     max_samples_per_send: 10000
     capacity: 20000
     max_shards: 30

scrape_configs:
  - job_name: "prom-edge1"
    static_configs:
      - targets:
          - 127.0.0.1:9090
  - job_name: "app"
    static_configs:
      - targets:
          - 10.164.246.145:8080
