{
 "title": "UP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Edge",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(sample_metric_counter1)" }
   ]
  },
  {
   "title": "up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{env}}" }
   ]
  },
  {
   "title": "sample_metric_gauge1",
   "type": "graph",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sample_metric_gauge1", "legendFormat": "{{env}}" }
   ]
  },
  {
   "title": "sample_metric_counter1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sample_metric_counter1)[1m]",
     "legendFormat": "{{env}}"
    }
   ]
  }
 ]
}