global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
     env: server  
 
remote_write:
  - url: http://vm:8428/api/v1/write

scrape_configs:
  - job_name: 'vm'
    static_configs:
    - targets: 
       - vm:8428

       
              
 
 
